// =============================================================
//  Naimul Hoque — CV (Backend / Systems variant)
//  Generated by cv-tailor. Editable source — compile yourself:
//      typst compile cv-backend.typ
// =============================================================

#set page(
  paper: "a4",
  margin: (x: 0.75in, top: 0.6in, bottom: 0.6in),
)
#set text(font: "New Computer Modern", size: 11pt)
#set par(
  spacing: 0.65em,
)
#set list(indent: 1em, spacing: 0.8em, marker: [·])

#let section(title) = {
  v(0.5em)
  text(weight: "bold", upper(title))
  v(-0.25em)
  line(length: 100%, stroke: 0.5pt)
  v(0.25em)
}

// ---------------- Header ----------------
#align(center, text(size: 24pt, weight: "bold", upper("Naimul Hoque")))
#v(0.35em)
#align(center)[
  Bath, England #h(0.5em) ⋄ #h(0.5em) Naimul\_Hoque\@outlook.com #h(0.5em) ⋄ #h(0.5em) 07719 260898
]
#v(0.5em)

// ---------------- Summary ----------------
// Yours to write — left as a placeholder by design.
#section("Personal Statement")
I am a highly motivated and skilled software engineer with a strong background in backend and systems development. I am experienced in designing and implementing complex software solutions, with a focus on performance, scalability, and maintainability. 
I am passionate about learning new technologies and continuously improving my skills to deliver high-quality software. This includes: a deep understanding of Linux systems, proficiency in Go and Python, and experience with cloud platforms such as AWS and GCP.
I always seek a challenge and enjoy working in collaborative environments where I can contribute to the success of the team and the organization.

// ---------------- Work Experience ----------------
#section("Work Experience")
*NCR Voyix* #h(1fr) _April 2020 – August 2026_ \
Role: Software Engineer I (Junior) → Software Engineer III (Senior)
- Modernised OS build system moving from a mutable container to a fully reproducible, immutable build pipeline.
- Enhanced Python build process by migrating to `uv` as the build system, improving package build and download speed, improving support for additional packages and architectures, and reducing security vulnerabilities via virtual environment isolation.
- Authored the design for a new OS-level daemon — JSON payload forwarding with a lease-based, "first-come first-served" exclusive-ownership model which was approved org-wide.
- Authored and delivered the RFC for a cloud-level container image verification system, taking it from proposal to production independently.
- Researched and designed a memory-efficient multi-process container model, producing department-wide documentation to set the pattern for future workloads.
- Built an intuitive terminal UI in Go for field engineers to configure system networking, improving operational efficiency.
- Overhauled onboarding and tooling documentation and ran regular internal tech talks (systemd, journald, NTP, PXE, engineering tooling), lifting team-wide depth.
- Mentored an intern through delivery of a key image-verification component via technical guidance and code review.

// ---------------- Skills ----------------
#section("Skills")
- *Languages:* Go, Python, Bash, Rust
- *Systems:* Linux (Ubuntu, Debian, Arch), systemd, daemons, concurrency, inter-process coordination, ARM cross-compilation, debian packaging, containerisation, networking, DNS, TLS, PKI
- *Infrastructure:* Docker, Kubernetes, Flux (GitOps), Helm, CI/CD pipelines
- *Cloud:* GCP (instance management, GKE, Artifact Registry), AWS (EC2, S3, ECS, API Gateway, Lambda, CloudWatch)
- *Observability:* Grafana, Prometheus

#pagebreak()
// ---------------- Certifications ----------------
#section("Certifications")
*AWS Certified Solutions Architect (Associate)* #h(1fr) _Awarded: September 2026_ \

// ---------------- Education ----------------
#section("Education")
*University of Bristol* #h(1fr) _September 2018 – July 2019_ \
MSc Computer Science & Electronics — Department of Engineering
\
\
*University of Bristol* #h(1fr) _September 2015 – July 2018_ \
BSc Computer Science & Electronics — Department of Engineering

// ---------------- Professional Project Highlights ----------------
#section("Professional Project Highlights")
*Enhanced Python Build Process - Python, debian packaging*
- Replaced legacy `setuptools` process with `uv`
- Improved build speed and reliability.
- Improved security posture by isolating builds in virtual environments.
- Improved support for additional packages and architectures.

*OS-Level Payload Daemon - Linux, Go, systemd*
- Designed a daemon that ingests JSON payloads and forwards them onward, with a lease-based ownership model:
  - First client to submit holds the daemon for a duration it specifies in the payload, letting it stream all of its payloads without contention before the lease releases.
- Carried design through org-wide review 
  - Engineering manager and org-wide technical lead
  - Ownership and lifecycle model accepted as proposed.
  
*Container Image Verification & Transparency Log - Kubernetes, GCP*
- Authored RFC and built system end-to-end, evolving from a single container to isolated pods across separate namespaces to demonstrate progressive security hardening.
- Designed namespace-level isolation and inter-component trust boundaries without external guidance.

// ---------------- Personal Project Highlights ----------------
#section("Personal Project Highlights")
*Multi-Server Telemetry via Kafka - AWS, Kafka*
- Built a multi-server telemetry system using Kafka, with a Go-based producer and consumer, to collect and process metrics from multiple servers in real-time.

*Prayer Alarm — Rust, ARM (Raspberry Pi), systemd*
- Forked and extended a time-calculation library, cross-compiled for ARM, and integrated it into a custom systemd service for reliable boot-time startup on a Raspberry Pi 2B.

*Home Kubernetes Lab — Kubernetes, Flux, WireGuard*
- Operates a production-grade cluster on TrueNAS SCALE (Calico, Flux GitOps, Traefik, cert-manager, Authentik, Grafana) with a self-hosted Git registry driving GitOps deployments over WireGuard.
